/**
 * Data.js - Données pour la checklist de déploiement
 * Contient toutes les données structurées utilisées dans l'application
 */

// Données des options cabinet provenant du fichier CabinetOptions.csv
const cabinetOptions = [
  {
    CabinetOptionId: 1,
    Nom: "AccesAnalytics",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 2,
    Nom: "AccesCalculsInterets",
    IsActive: 1,
    Domaine: "CalculsInterets",
    Description:
      "Permet de beneficier du calcul d'intérêts dans Néo (paramétrage, CRUD et tuiles dashboard associées)",
  },
  {
    CabinetOptionId: 3,
    Nom: "AncrageOutlook",
    IsActive: 1,
    Domaine: "ComplementOutlookWPF",
    Description:
      "Bloque en place les fenetres du complement outlook WPF, en cachant les option de déplacement",
  },
  {
    CabinetOptionId: 4,
    Nom: "ArrondiTempsPasses",
    IsActive: 1,
    Domaine: "TempsPasses",
    Description:
      "Permet d'avoir l'arrondi des temps dans la fiche personne et le parametre avancé",
  },
  {
    CabinetOptionId: 5,
    Nom: "CalculInteretAnneesBissextiles",
    IsActive: 0,
    Domaine: "CalculsInterets",
    Description:
      "Le calcul d'interêts comptabilise bien le jour supplementaire des années bissextiles",
  },
  {
    CabinetOptionId: 6,
    Nom: "CalculInteretAvantOperation",
    IsActive: 1,
    Domaine: "CalculsInterets",
    Description:
      "Le calcul d'interêts prend en compte comme date de fin du calcul la veille de la date en cours",
  },
  {
    CabinetOptionId: 7,
    Nom: "CalculInteretCapitalisationAnnuelle",
    IsActive: 1,
    Domaine: "CalculsInterets",
    Description:
      "Le calcul d'interêts offre l'option de calcul de capitalisation annuelle",
  },
  {
    CabinetOptionId: 8,
    Nom: "CalculInteretDifference",
    IsActive: 0,
    Domaine: "CalculsInterets",
    Description: "Le calcul d'interêts offre l'option de calcul par difference",
  },
  {
    CabinetOptionId: 9,
    Nom: "Categorie",
    IsActive: 1,
    Domaine: "Documents",
    Description:
      "Permet l'utilisation des catégories pour le tri automatique des documents",
  },
  {
    CabinetOptionId: 10,
    Nom: "ChronoDossier",
    IsActive: 1,
    Domaine: null,
    Description: "Permet d'afficher un chrono dans le dossier",
  },
  {
    CabinetOptionId: 11,
    Nom: "CommunicationStructuree",
    IsActive: 0,
    Domaine: "FacturesBE",
    Description:
      "Permet l'utilisation de la communication structurée pour les factures BE",
  },
  {
    CabinetOptionId: 12,
    Nom: "ComplementInformation",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet l'ajout d'un champ \"complement d'information\" dans les parties d'un dossier.",
  },
  {
    CabinetOptionId: 13,
    Nom: "CompteAuxiliaireErrorText",
    IsActive: 0,
    Domaine: null,
    Description:
      "Gere l'apparition d'un message si le compte auxiliaire client renseigné existe déjà en base",
  },
  {
    CabinetOptionId: 14,
    Nom: "DecisionAttaquee",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet de préciser quelles decisions sont attaquées dans les dossiers, dans les infos de la juridiction",
  },
  {
    CabinetOptionId: 15,
    Nom: "DeepSearch",
    IsActive: 0,
    Domaine: null,
    Description: "Permet d'activer la recherche avancée dans LéA",
  },
  {
    CabinetOptionId: 16,
    Nom: "DeleteOnlylastFacture",
    IsActive: 0,
    Domaine: null,
    Description: "Limite la supression de facture à la derniere créée",
  },
  {
    CabinetOptionId: 17,
    Nom: "DetectionDoublonMailOutlook",
    IsActive: 1,
    Domaine: "ComplementOutlookWPF",
    Description:
      "Permet au complement outlook de signaler si un mail similaire a déjà été rattaché au dossier",
  },
  {
    CabinetOptionId: 18,
    Nom: "DPA",
    IsActive: 0,
    Domaine: "DPA",
    Description: "Permet l'utilisation de la DPA, équivalent d'E-barreau Belge",
  },
  {
    CabinetOptionId: 19,
    Nom: "Ebarreau",
    IsActive: 1,
    Domaine: null,
    Description: "Permet de voir le menu E-barreau dans le menu de gauche",
  },
  {
    CabinetOptionId: 20,
    Nom: "Ecostaff",
    IsActive: 1,
    Domaine: null,
    Description: "Permet d'afficher l'accès à ecostaff dans le menu de gauche",
  },
  {
    CabinetOptionId: 21,
    Nom: "EffacementRGPD",
    IsActive: 1,
    Domaine: "ModuleRGPD",
    Description:
      "Permet l'accès au module d'effacement RGPD des personnes et dossiers",
  },
  {
    CabinetOptionId: 22,
    Nom: "EtatPrefacturationInteractif",
    IsActive: 0,
    Domaine: null,
    Description: "Permet de pouvoir faire un état de préfa interactif ",
  },
  {
    CabinetOptionId: 23,
    Nom: "FiltreFavori",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet d'enregistrer des filtres pour faciliter les prochaines recherches",
  },
  {
    CabinetOptionId: 24,
    Nom: "FraisFournisseur",
    IsActive: 1,
    Domaine: null,
    Description: "Permet l'utilisation des frais fournisseurs",
  },
  {
    CabinetOptionId: 25,
    Nom: "IdentificationTemps",
    IsActive: 0,
    Domaine: null,
    Description:
      "Permet d'avoir les valeurs perdu et traité dans l'état des TP lors de la factu et de pouvoir scinder un temps dans la factu",
  },
  {
    CabinetOptionId: 26,
    Nom: "Juridique",
    IsActive: 1,
    Domaine: null,
    Description:
      "Débloque l'accés aux onglets des matières juridiques (IFU, RCM, Suivi des sociétés...) (et aux dossiers gris maybe)",
  },
  {
    CabinetOptionId: 27,
    Nom: "LectureCarteIdentite",
    IsActive: 0,
    Domaine: "PersonnesBE",
    Description:
      "Permet d'acceder à la fonctionnalité de lecture de carte d'identité en place en Belgique",
  },
  {
    CabinetOptionId: 28,
    Nom: "LiaisonFraisTempsPassesAir",
    IsActive: 0,
    Domaine: "TempsPasses",
    Description:
      "Active la liaison des codes d'activités pour les Temps Passes et les frais (habituellement réservé à Néo)",
  },
  {
    CabinetOptionId: 29,
    Nom: "LibelleMatiereAvecTypeDossier",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet l'affichage du type de dossier associé à la matière dans les listes de filtres par matière (particulièrement utile en juridique)",
  },
  {
    CabinetOptionId: 30,
    Nom: "ListeNewLook",
    IsActive: 1,
    Domaine: "GrillesNeo",
    Description:
      "Permet à l'utilisateur de pouvoir redimensionner et déplacer les colonnes des grilles dans Néo",
  },
  {
    CabinetOptionId: 31,
    Nom: "LogicielComptaCasper",
    IsActive: 0,
    Domaine: null,
    Description:
      "Ajoute le logiciel Casper (aka Secib Compta) à la liste des logiciels de comptabilité dans la liste déroulante du paramétrage de comptabilité",
  },
  {
    CabinetOptionId: 32,
    Nom: "Meetlaw",
    IsActive: 1,
    Domaine: null,
    Description: "Donne accès à Meetlaw dans le menu de gauche",
  },
  {
    CabinetOptionId: 33,
    Nom: "MicroServiceDashboard",
    IsActive: 0,
    Domaine: "MicroServiceDashboard",
    Description: "Permet l'affichage du nouveau dashboard µService",
  },
  {
    CabinetOptionId: 34,
    Nom: "MicroServiceDashboardPilote",
    IsActive: 1,
    Domaine: "MicroServiceDashboard",
    Description:
      "Permet l'accès à la fenêtre de retour utilisateur en plus de l'affichage du dashboard. Un switch vers l'ancien dash est également disponible si l'option MicroServiceDashboard est à False en DB",
  },
  {
    CabinetOptionId: 35,
    Nom: "MobileTachePrioritaire",
    IsActive: 1,
    Domaine: "Mobile",
    Description:
      "Permet d'activer la notion de taches prio dans Mobile (n'a surement plus lieu d'être)",
  },
  {
    CabinetOptionId: 36,
    Nom: "ModePaiement",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet de sélectionner le mode de paiement lors de la saisie de règlement",
  },
  {
    CabinetOptionId: 37,
    Nom: "MultiComptabilite",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet de gérer plusieurs comptabilité au sein d'un cabinet. Pratique répandue dans les SELARL ou cabinet Belge.",
  },
  {
    CabinetOptionId: 38,
    Nom: "MultiDevise",
    IsActive: 0,
    Domaine: null,
    Description:
      "Permet d'avoir la multi devise dans neo (parametre, facture,reglement, client..)",
  },
  {
    CabinetOptionId: 39,
    Nom: "NumerotationManuelleDossier",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 40,
    Nom: "NumerotationSite",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 41,
    Nom: "OutlookClassementResponseMail",
    IsActive: 1,
    Domaine: "ComplementOutlookWPF",
    Description:
      "Permet au complement de proposer un dossier de classement lors de la réponse à un mail déjà rangé ",
  },
  {
    CabinetOptionId: 42,
    Nom: "ParametrageEmail",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 43,
    Nom: "ParametreRelance",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet de rattacher les doc de factu dans les mails ou impression de relance (paramètres avancés)",
  },
  {
    CabinetOptionId: 44,
    Nom: "RattachementAvanceOutlook",
    IsActive: 1,
    Domaine: "ComplementOutlookWPF",
    Description:
      "Permet dans le complément Outlook de rattacher plusieurs emails simultanément",
  },
  {
    CabinetOptionId: 45,
    Nom: "RattachementIntelligentOutlook",
    IsActive: 1,
    Domaine: "ComplementOutlookWPF",
    Description:
      "Permet au complement de proposer un dossier de classement des mails reçus",
  },
  {
    CabinetOptionId: 46,
    Nom: "Repartition",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet d'afficher la gestion de la répartition de l'encaissement dans les dossiers",
  },
  {
    CabinetOptionId: 47,
    Nom: "SecibVoIP",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permets d'accéder au service de suivi des appels (création de tickets avec temps passés)",
  },
  {
    CabinetOptionId: 48,
    Nom: "Strada",
    IsActive: 0,
    Domaine: "ComptaBE",
    Description:
      "Permet l'utilisation des Stradalex, utilisé pour la comptabilité Belge",
  },
  {
    CabinetOptionId: 49,
    Nom: "SuggestionParapheur",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 50,
    Nom: "SynchroPersonneOutlook",
    IsActive: 0,
    Domaine: null,
    Description: "Synchronisation des personnes vers Outlook",
  },
  {
    CabinetOptionId: 51,
    Nom: "TacheMultiIntervenant",
    IsActive: 1,
    Domaine: "Taches",
    Description: "Permet l'envoi d'une tache à plusieurs intervenants",
  },
  {
    CabinetOptionId: 52,
    Nom: "TempsPasseParapheur",
    IsActive: 1,
    Domaine: "TempsPasses",
    Description:
      "Permet l'affichage d'un compteur dans la prévisu des docs au parapheur, pouvant génerer un temps passé si supérieur au temps paramétré dans la compte de l'user",
  },
  {
    CabinetOptionId: 53,
    Nom: "TempsPassesRecalcul",
    IsActive: 1,
    Domaine: "TempsPasses",
    Description: "Active la présence du bouton de recalcul des temps passés",
  },
  {
    CabinetOptionId: 54,
    Nom: "TypeFacturier",
    IsActive: 0,
    Domaine: null,
    Description:
      'Permet d\'afficher le champs "Type de Facturier" dans le paramétrage de ceux-ci. Remonte les types Vente et note de crédit/Avoirs',
  },
  {
    CabinetOptionId: 55,
    Nom: "VerificationLicenceAR24",
    IsActive: 0,
    Domaine: null,
    Description:
      "Permet de vérifier si une licence est active pour le cabinet sur AR24",
  },
  {
    CabinetOptionId: 56,
    Nom: "VerificationLicenceYousign",
    IsActive: 0,
    Domaine: null,
    Description:
      "Permet de vérifier si une licence est active pour le cabinet sur la eSignature",
  },
  {
    CabinetOptionId: 57,
    Nom: "EquipeAgenda",
    IsActive: 1,
    Domaine: null,
    Description: null,
  },
  {
    CabinetOptionId: 58,
    Nom: "Budget",
    IsActive: 0,
    Domaine: null,
    Description: "Permet de créer des budgets",
  },
  {
    CabinetOptionId: 59,
    Nom: "PersonnalisationOnglets",
    IsActive: 1,
    Domaine: "MicroServiceDashboard",
    Description:
      "Permet l'accès à la gestion des onglets (creation, renommage et suppression des onglets)",
  },
  {
    CabinetOptionId: 60,
    Nom: "ParametrageEtMultiInstanceWidget",
    IsActive: 1,
    Domaine: "MicroServiceDashboard",
    Description:
      "Permet l'ajout de plusieurs instances d'une même tuile et leur paramétrage (visibilité de la section de paramétrage dans le volet d'information et paramétrage",
  },
  {
    CabinetOptionId: 61,
    Nom: "DossierConfidentialiteHorsResponsable",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet d'activer un droit qui permet de rendre un dossier confidentiel si on est pas le responsable de celui-ci",
  },
  {
    CabinetOptionId: 62,
    Nom: "ImpayeRelanceOngletClient",
    IsActive: 1,
    Domaine: null,
    Description: "Permet de voir l'onglet client dans les impayes",
  },
  {
    CabinetOptionId: 63,
    Nom: "AffichageAvanceTauxHoraires",
    IsActive: 1,
    Domaine: null,
    Description:
      "Permet d'afficher la colonne taux engagé dans les TP et les colonnes taux engagé, taux facturé dans la facturation",
  },
  {
    CabinetOptionId: 64,
    Nom: "Fragments",
    IsActive: 1,
    Domaine: "MicroServiceFragments",
    Description: "Permet l'accès au module complément office Fragments",
  },
  {
    CabinetOptionId: 65,
    Nom: "FacturationMultiDossierDepuisDossier",
    IsActive: 0,
    Domaine: null,
    Description: "Permet de facturer plusieurs dossiers à partir d un dossier",
  },
  {
    CabinetOptionId: 66,
    Nom: "ProformaComptabilise",
    IsActive: 0,
    Domaine: "SecibOnline",
    Description:
      "Si actif (valeur 1), alors les proforma remontent dans le calcul du solde, si désactivé (valeur 0) alors le solde du dossier dans le facturé ne les comptabilise pas.",
  },
];

// Checklist des fonctionnalités avec temps
const checklistData = [
  // PARAMÉTRAGE
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "UTILISATEURS",
    FONCTIONNALITES:
      "Utilisateurs (par user)\n- Activation/désactivation\n- Tx horaire, Profil, Représentation",
    Attention: "",
    TEMPS: "00:02:00",
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "UTILISATEURS",
    FONCTIONNALITES: "Profils",
    Attention: "",
    TEMPS: "00:30:00",
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "UTILISATEURS",
    FONCTIONNALITES: "Equipes",
    Attention: "",
    TEMPS: "00:01:00",
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "UTILISATEURS",
    FONCTIONNALITES: "Modèles de taux",
    Attention: "",
    TEMPS: "00:01:00",
  },
  /* {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "MATRICES",
    FONCTIONNALITES: "Matrices",
    Attention: "Warning",
    TEMPS: "",
  },*/
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "MATRICES",
    FONCTIONNALITES: "Modification fonds de page",
    Attention: "",
    TEMPS: "00:10:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "MATRICES",
    FONCTIONNALITES: "Modification matrices existantes",
    Attention: "",
    TEMPS: "",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "MATRICES",
    FONCTIONNALITES: "Matrices existantes à récupérer",
    Attention: "",
    TEMPS: "",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "MATRICES",
    FONCTIONNALITES: "Nettoyage des matrices",
    Attention: "",
    TEMPS: "00:01:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "NUMÉROTATION",
    FONCTIONNALITES: "Numérotation dossiers",
    Attention: "",
    TEMPS: "00:05:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "NUMÉROTATION",
    FONCTIONNALITES: "Numérotation factures",
    Attention: "",
    TEMPS: "00:05:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    SOUS_SECTION: "NUMÉROTATION",
    FONCTIONNALITES: "Numérotation archives",
    Attention: "",
    TEMPS: "00:05:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Sites",
    Attention: "",
    TEMPS: "00:15:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Arborescences",
    Attention: "",
    TEMPS: "00:15:00",
    TYPE: "number",
    DEFAULT_VALUE: 0,
  },
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Codes activités",
    Attention: "",
    TEMPS: "01:00:00",
    TYPE: "switch",
  },
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Dashboard",
    Attention: "",
    TEMPS: "",
    TYPE: "switch",
  },
  /* {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Codes activités",
    Attention: "",
    TEMPS: "01:00:00",
  },*/
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Actions liées",
    Attention: "",
    TEMPS: "",
    TYPE: "switch",
  },
  {
    THEME: "PARAMÉTRAGE",
    FONCTIONNALITES: "Infos complémentaires",
    Attention: "",
    TEMPS: "",
    TYPE: "switch",
  },
  // CABINET OPTION
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "EtatPrefacturationInteractif",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "EtatPrefacturationInteractif",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "Budget",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Budget",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "AccesAnalytics",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "AccesAnalytics",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "CALCULS & FINANCES",
    FONCTIONNALITES: "AccesCalculsInterets",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "AccesCalculsInterets",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "AncrageOutlook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "AncrageOutlook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "ArrondiTempsPasses",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ArrondiTempsPasses",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "CALCULS & FINANCES",
    FONCTIONNALITES: "CalculInteretAnneesBissextiles",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CalculInteretAnneesBissextiles",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "CALCULS & FINANCES",
    FONCTIONNALITES: "CalculInteretAvantOperation",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CalculInteretAvantOperation",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "CALCULS & FINANCES",
    FONCTIONNALITES: "CalculInteretCapitalisationAnnuelle",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CalculInteretCapitalisationAnnuelle",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "CALCULS & FINANCES",
    FONCTIONNALITES: "CalculInteretDifference",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CalculInteretDifference",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "Categorie",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Categorie",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "ChronoDossier",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ChronoDossier",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "CommunicationStructuree",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CommunicationStructuree",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "ComplementInformation",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ComplementInformation",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "CompteAuxiliaireErrorText",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "CompteAuxiliaireErrorText",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "DecisionAttaquee",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DecisionAttaquee",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "DeepSearch",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DeepSearch",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "DeleteOnlylastFacture",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DeleteOnlylastFacture",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "DetectionDoublonMailOutlook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DetectionDoublonMailOutlook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "DPA",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DPA",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "Ebarreau",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Ebarreau",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "Ecostaff",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Ecostaff",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "EffacementRGPD",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "EffacementRGPD",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "FiltreFavori",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "FiltreFavori",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "FraisFournisseur",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "FraisFournisseur",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "IdentificationTemps",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "IdentificationTemps",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "Juridique",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Juridique",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "LectureCarteIdentite",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "LectureCarteIdentite",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "LiaisonFraisTempsPassesAir",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "LiaisonFraisTempsPassesAir",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "LibelleMatiereAvecTypeDossier",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "LibelleMatiereAvecTypeDossier",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "ListeNewLook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ListeNewLook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "LogicielComptaCasper",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "LogicielComptaCasper",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "Meetlaw",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Meetlaw",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "MicroServiceDashboard",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "MicroServiceDashboard",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "MicroServiceDashboardPilote",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "MicroServiceDashboardPilote",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "MobileTachePrioritaire",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "MobileTachePrioritaire",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "ModePaiement",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ModePaiement",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "MultiComptabilite",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "MultiComptabilite",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "MultiDevise",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "MultiDevise",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "NumerotationManuelleDossier",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "NumerotationManuelleDossier",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "NumerotationSite",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "NumerotationSite",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "OutlookClassementResponseMail",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "OutlookClassementResponseMail",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "ParametrageEmail",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ParametrageEmail",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "ParametreRelance",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ParametreRelance",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "RattachementAvanceOutlook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "RattachementAvanceOutlook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "RattachementIntelligentOutlook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "RattachementIntelligentOutlook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "Repartition",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Repartition",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "SecibVoIP",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "SecibVoIP",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "Strada",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Strada",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "SuggestionParapheur",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "SuggestionParapheur",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "SynchroPersonneOutlook",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "SynchroPersonneOutlook",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "TacheMultiIntervenant",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "TacheMultiIntervenant",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "TempsPasseParapheur",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "TempsPasseParapheur",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "TempsPassesRecalcul",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "TempsPassesRecalcul",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "TypeFacturier",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "TypeFacturier",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "VerificationLicenceAR24",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "VerificationLicenceAR24",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "VerificationLicenceYousign",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "VerificationLicenceYousign",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "EquipeAgenda",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "EquipeAgenda",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "PersonnalisationOnglets",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "PersonnalisationOnglets",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ANALYSE & REPORTING",
    FONCTIONNALITES: "ParametrageEtMultiInstanceWidget",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ParametrageEtMultiInstanceWidget",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION DOSSIERS",
    FONCTIONNALITES: "DossierConfidentialiteHorsResponsable",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "DossierConfidentialiteHorsResponsable",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "ImpayeRelanceOngletClient",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ImpayeRelanceOngletClient",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "AffichageAvanceTauxHoraires",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "AffichageAvanceTauxHoraires",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "ÉDITION & VALIDATION",
    FONCTIONNALITES: "Fragments",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "Fragments",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "FacturationMultiDossierDepuisDossier",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "FacturationMultiDossierDepuisDossier",
  },
  {
    THEME: "CABINET OPTION",
    SOUS_SECTION: "GESTION FINANCIÈRE",
    FONCTIONNALITES: "ProformaComptabilise",
    Attention: "Warning",
    TEMPS: "",
    PRODUIT: ["NEO"],
    TYPE: "checkbox",
    csvName: "ProformaComptabilise",
  },

  // MODULES COMPLEMENTAIRES
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "CONNECTIVITÉ",
    FONCTIONNALITES: "Online",
    Attention: "Warning",
    TEMPS: "01:00:00",
    csvName: "Online",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "REPORTING",
    FONCTIONNALITES: "Analytics",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Analytics",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "GESTION DOCUMENTAIRE",
    FONCTIONNALITES: "DigitalDoc",
    Attention: "Licences",
    TEMPS: "01:50:00",
    csvName: "DigitalDoc",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "PRODUCTIVITÉ",
    FONCTIONNALITES: "DictaPlus",
    Attention: "Licences",
    TEMPS: "00:50:00",
    csvName: "DictaPlus",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "MÉTIER",
    FONCTIONNALITES: "Juridique",
    Attention: "Warning",
    TEMPS: "07:00:00",
    csvName: "Juridique",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "INTELLIGENCE ARTIFICIELLE",
    FONCTIONNALITES: "BRAIN",
    Attention: "",
    TEMPS: "02:00:00",
    csvName: "BRAIN",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "COMMUNICATION",
    FONCTIONNALITES: "RPVA",
    Attention: "Warning + Licences",
    TEMPS: "01:00:00",
    csvName: "RPVA",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "MÉTIER",
    FONCTIONNALITES: "Saisie immobilière",
    Attention: "",
    TEMPS: "03:30:00",
    csvName: "Saisie immobilière",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "PRODUCTIVITÉ",
    FONCTIONNALITES: "Actions liées",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Actions liées",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "ACCOMPAGNEMENT",
    FONCTIONNALITES: "Suivi personnalisé",
    Attention: "",
    TEMPS: "10:00:00",
    csvName: "Suivi personnalisé",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "ACCOMPAGNEMENT",
    FONCTIONNALITES: "Accompagnement sur mesure",
    Attention: "",
    TEMPS: "03:00:00",
    csvName: "Accompagnement sur mesure",
  },
  {
    THEME: "MODULES COMPLEMENTAIRES",
    SOUS_SECTION: "INTÉGRATION",
    FONCTIONNALITES: "Interface comptable",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Interface comptable",
  },

  // FORMATIONS
  // Modules unitaires
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Online",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Online",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Analytics",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Analytics",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "DigitalDoc",
    Attention: "",
    TEMPS: "01:50:00",
    csvName: "DigitalDoc",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "DictaPlus",
    Attention: "",
    TEMPS: "00:50:00",
    csvName: "DictaPlus",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Juridique",
    Attention: "",
    TEMPS: "07:00:00",
    csvName: "Juridique",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "BRAIN",
    Attention: "",
    TEMPS: "02:00:00",
    csvName: "BRAIN",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "RPVA",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "RPVA",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Saisie immobilière",
    Attention: "",
    TEMPS: "03:30:00",
    csvName: "Saisie immobilière",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Actions liées",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Actions liées",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Suivi personnalisé",
    Attention: "",
    TEMPS: "10:00:00",
    csvName: "Suivi personnalisé",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Accompagnement sur mesure",
    Attention: "",
    TEMPS: "03:00:00",
    csvName: "Accompagnement sur mesure",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES",
    FONCTIONNALITES: "Interface comptable",
    Attention: "",
    TEMPS: "01:00:00",
    csvName: "Interface comptable",
  },
  // Packs démarrage complet
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK DÉMARRAGE COMPLET",
    FONCTIONNALITES: "Gestion de dossier & production",
    Attention: "Par groupe de 8",
    TEMPS: "03:30:00",
    csvName: "Gestion de dossier & production",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK DÉMARRAGE COMPLET",
    FONCTIONNALITES: "Gestion financière",
    Attention: "Par groupe de 8",
    TEMPS: "03:30:00",
    csvName: "Gestion financière",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK DÉMARRAGE COMPLET",
    FONCTIONNALITES: "Gestion intégrée",
    Attention: "Par groupe de 8",
    TEMPS: "03:30:00",
    csvName: "Gestion intégrée",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK DÉMARRAGE COMPLET",
    FONCTIONNALITES: "Assistance au démarrage",
    Attention: "Par groupe de 8",
    TEMPS: "03:30:00",
    csvName: "Assistance au démarrage",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK DÉMARRAGE COMPLET",
    FONCTIONNALITES: "Validation des connaissances",
    Attention: "Par groupe de 8",
    TEMPS: "03:30:00",
    csvName: "Validation des connaissances",
  },
  // Packs secrétariat juridique
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "PACK SECRÉTARIAT JURIDIQUE",
    FONCTIONNALITES: "Pack complet",
    Attention: "",
    TEMPS: "07:00:00",
    csvName: "Pack complet",
  },
  // Modules à la carte
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES SECRÉTARIAT JURIDIQUE",
    FONCTIONNALITES: "#1 - La gestion administrative",
    Attention: "",
    TEMPS: "03:30:00",
    csvName: "#1 - La gestion administrative",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "MODULES SECRÉTARIAT JURIDIQUE",
    FONCTIONNALITES: "#2 - Les opérations",
    Attention: "",
    TEMPS: "03:30:00",
    csvName: "#2 - Les opérations",
  },
  {
    THEME: "FORMATIONS",
    SOUS_SECTION: "A LA CARTE",
    FONCTIONNALITES: "Passer de AIR à NEO",
    Attention: "",
    TEMPS: "03:30:00",
    csvName: "Passer de AIR à NEO",
  },
];

// Tableau de correspondance modules/formations et produits compatibles
const moduleProduits = {
  // Correspondances spécifiques
  // CABINET OPTION
  "Préfa intéractive": ["NEO"],
  Budget: ["NEO"],
  "Facturation automatique": ["NEO"],
  "Règlement automatique": ["NEO"],
  "Modèles de factures": ["NEO", "AIR"],
  "Gestion des avances": ["NEO"],
  "Workflow de facturation": ["NEO"],
  "Modèles convention d'honoraires": ["NEO"],
  "Frais forfaitaires": ["NEO"],
  DIGIACT: ["NEO"],
  "Modèles d'actes": ["NEO", "AIR"],
  "Paramètres d'imports": ["NEO", "AIR"],
  "Modèles d'export": ["NEO", "AIR"],
  "Modèles de lettres": ["NEO", "AIR"],
  "Modèles emails": ["NEO", "AIR"],

  // MODULES COMPLEMENTAIRES
  Online: ["NEO"],
  Analytics: ["NEO"],
  DigitalDoc: ["NEO", "AIR"],
  DictaPlus: ["NEO"],
  Juridique: ["NEO"],
  BRAIN: ["NEO"],
  RPVA: ["NEO", "AIR", "ADAPPS"],
  "Saisie immobilière": ["NEO"],
  "Actions liées": ["NEO", "ADAPPS"],
  "Suivi personnalisé": ["NEO"],
  "Accompagnement sur mesure": ["NEO", "ADAPPS"],
  "Interface comptable": ["NEO", "AIR"],

  // FORMATIONS
  "DEMARRAGE COMPLET - Gestion de dossier & production": ["NEO"],
  "DEMARRAGE COMPLET - Gestion financière": ["NEO"],
  "DEMARRAGE COMPLET - Gestion intégrée": ["NEO"],
  "DEMARRAGE COMPLET - Assistance au démarrage": ["NEO"],
  "DEMARRAGE COMPLET - Validation des connaissances": ["NEO"],
  "SECRETARIAT JURIDIQUE - La gestion administrative": ["NEO"],
  "SECRETARIAT JURIDIQUE - Les opérations": ["NEO"],
  "SECRETARIAT JURIDIQUE - Pack complet": ["NEO"],
  "SECRETARIAT JURIDIQUE - Pack complet (Gestion administrative + Opérations)":
    ["NEO"],
  "SECRETARIAT JURIDIQUE #1 - La gestion administrative": ["NEO"],
  "SECRETARIAT JURIDIQUE #2 - Les opérations": ["NEO"],
  "A LA CARTE - Passer de AIR à NEO": ["NEO"],

  // Correspondances plus génériques pour les cas non explicites
  Online: ["NEO"],
  Analytics: ["NEO"],
  DigitalDoc: ["NEO", "AIR"],
  DictaPlus: ["NEO"],
  Juridique: ["NEO"],
  BRAIN: ["NEO"],
  RPVA: ["NEO", "AIR", "ADAPPS"],
  Saisie: ["NEO"],
  Actions: ["NEO", "ADAPPS"],
  Suivi: ["NEO"],
  Accompagnement: ["NEO", "ADAPPS"],
  Interface: ["NEO", "AIR"],
};

// Tableau de correspondance scénario/fonctionnalités
// Exemple : chaque clé est un scénario, la valeur est un tableau de fonctionnalités (ou regex, ou index)
const scenarioFeatures = {
  separation: [
    // Exemples :
    "Echange avec le client",
    "Utilisateurs (par user)",
    // ...
  ],
  fusion: [
    // ...
  ],
  AIRversAIR: [
    // ...
  ],
  NEOversNEO: [
    // ...
  ],
  AIRversNEO: [
    // ...
  ],
  AutreversNEO: [
    // ...
  ],
};
