# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json
# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master

resources:
  - repo: self

variables:
  # Groupe de variables sécurisé défini dans Azure DevOps (DockerHubVars)
  #   contient : dockerHubNamespace
  # Les variables listées ci-dessous sont injectées au runtime.
  - name: tag
    value: "$(Build.BuildId)"
  - name: dockerRegistryServiceConnection
    value: "DockerHubConnection"
  - name: dockerRepository
    value: "$(dockerHubNamespace)/onboardingclient-frontend"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push image
            inputs:
              command: buildAndPush
              repository: "$(dockerRepository)"
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              containerRegistry: "$(dockerRegistryServiceConnection)"
              tags: |
                $(tag)
                latest
