# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  dockerRegistryServiceConnection: "DockerHubConnection"
  # Le namespace Docker Hub (nom d'utilisateur) doit être fourni dans les variables du pipeline
  # ou via un groupe de variables sécurisé nommé par exemple "DockerHubVars".
  # Il n'apparaît donc pas en clair dans ce fichier.
  dockerRepository: "$(dockerHubNamespace)/onboardingclient-frontend"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push image
            inputs:
              command: buildAndPush
              repository: "$(dockerRepository)"
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              buildContext: "$(Build.SourcesDirectory)"
              containerRegistry: "$(dockerRegistryServiceConnection)"
              tags: |
                $(tag)
                latest
